In [1]:
import pandas as pd

In [2]:
titanic = pd.read_csv("/Users/sajin/Datasets/tested.csv")

In [4]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
titanic["Age"].mean()

np.float64(30.272590361445783)

In [8]:
titanic[["Age","Fare"]].median()

Age     27.0000
Fare    14.4542
dtype: float64

In [9]:
titanic[["Age","Fare"]].describe()

              Age        Fare
count  332.000000  417.000000
mean    30.272590   35.627188
std     14.181209   55.907576
min      0.170000    0.000000
25%     21.000000    7.895800
50%     27.000000   14.454200
75%     39.000000   31.500000
max     76.000000  512.329200

In [10]:
titanic.agg({
    "Age":["min","max","median","skew"],
    "Fare":["min","max","median","mean"]
})

              Age        Fare
min      0.170000    0.000000
max     76.000000  512.329200
median  27.000000   14.454200
skew     0.457361         NaN
mean          NaN   35.627188

In [11]:
titanic.groupby(["Sex","Pclass"])["Fare"].mean()

Sex     Pclass
female  1         115.591168
        2          26.438750
        3          13.735129
male    1          75.586551
        2          20.184654
        3          11.826350
Name: Fare, dtype: float64

In [12]:
titanic['Pclass'].value_counts()

Pclass
3    218
1    107
2     93
Name: count, dtype: int64